### ISSUE TITLE
Registration does not work

### ISSUE THREAD

**Issue by judemont** [PeerBrain/web-client#2]
Hello,
When I'm trying to register I have this error: 

![printscreen](https://github.com/PeerBrain/web-client/assets/96385330/2d402b15-d7b8-4bf7-8ec1-4455f7de821f)

**Comment by andrewstech** [comment]
So the web client is currently a work in progress so some features such as registration might not work properly. However most functions are not yet intergraded. The best way to access peerbrain currently is via the CLI

**Comment by judemont** [comment]
Okay, thanks.
